### PR TITLE
add wrap for ffmpeg 4.1

### LINKED ISSUE #130: Failing to compile on Archlinux
Hi, I'm getting this error:
```
ERROR: LoadError: LoadError: could not open file /home/adria/.julia/packages/VideoIO/PIgWQ/src/ffmpeg/AVUtil/v56/LIBAVUTIL.jl
```
Which looks really similar to: https://github.com/kmsquire/VideoIO.jl/issues/87. Except that in this case, it's the `v56` that does not exist.

### PR DESCRIPTION
**Pull request by clouds56**
fixes #130.

There're lots of changes in Clang.jl. I'm not sure it gets everything works.

### CODE REVIEW

**Comment by ryan4yin** [comment]
it works for me, on manjaro 18.0

**Comment by ianshmean** [comment]
Works for me on MacOS (Mojave)

**Comment by ianshmean** [comment]
I do get a `Warning: Package VideoIO does not have Libdl in its dependencies` error however

**Comment by ianshmean** [comment]
@kmsquire can this be merged soon? I'd like to rely on this package, and I'm a little concerned about master falling far out of date. Happy to help review etc.

**Comment by kmsquire** [comment]
@clouds56, thank you for your work here, and sorry for the long delay.
@ianshmean, thanks for the ping.

For both of you, if you're interested in being added as collaborators here, please let me know.

**Comment by ianshmean** [comment]
Thanks @kmsquire ! Happy to help out as a (cautious) collaborator

**Pull request merged**
