### PR TITLE
test on 0.3 on travis

### PR DESCRIPTION
**Pull request by tkelman**
still supported according to REQUIRE

### CODE REVIEW

**Comment by kmsquire** [comment]
Thanks!  I actually just forgot to bump REQUIRE (sorry to merge so quickly--will wait for comments next time), but I appreciate the work you put in to fix the tests. Will merge and tag, but then probably drop support for v0.3 on the next commit (and bump the minor version).

**Comment by tkelman** [comment]
There may still be issues not exactly coemvered by the tests, hard to say. So either a new tag where it's green on 0.3, or just raising the minimum on the most recent tag would work.

**Comment by kmsquire** [comment]
Would you mind squashing, and then merging?  I gave you commit access.

**Comment by tkelman** [comment]
auto squash button okay by you?

**Comment by kmsquire** [comment]
Funny, I was looking for that and didn't see it.

**Comment by tkelman** [comment]
You have to click the merge button then select the squash option before clicking confirm.

**Comment by kmsquire** [comment]
Anyway, thanks for your help and time (and for all of the effort you put into Julia!)

**Comment by kmsquire** [comment]
Ah, got it.

**Pull request merged**
